#!/bin/bash

echo "### ALL NODES"
% for obj in db.get_nodes().unwrap():
echo "${', '.join(obj.layout.tags)}" > $HOME/tags.txt
% if "adam" in node.layout.tags:
echo "[ID: ${obj.instance_id}] Name: ${obj.instance_name} || Connection: ${obj.layout.username}@${obj.public_ip} || Provider: ${obj.layout.provider}"
% endif 
% endfor
echo "### ALL NODES"


echo "### CURRENT NODE"
echo "[ID: ${node.instance_id}] Name: ${node.instance_name} || Connection: ${node.layout.username}@${node.public_ip} || Provider: ${node.layout.provider}"
echo "### CURRENT NODE"


mkdir -p $HOME/output
touch $HOME/output/test.xml