#!/bin/bash
<%! from ogc.templatetags import run, header, hr %>

<%namespace name="utils" file="/functions.mako"/>

${header('Connection information')}
echo "id: ${node.instance_id}"
echo "name: ${node.instance_name}"
echo "connection: ${node.layout.username}@${node.public_ip}"
echo "provider ${node.layout.provider}"
${hr()}

${run('ls', '/', l=True, h=True)}


${header('All nodes')}
% for obj in nodes:
echo "id: ${obj.instance_id}"
echo "name: ${obj.instance_name}"
echo "connection: ${obj.layout.username}@${obj.public_ip}"
echo "provider ${obj.layout.provider}"
% endfor
${header('All nodes finished')}




${run('mkdir', node.layout.remote_path + "/output", p=True)} && \
${run('touch', node.layout.remote_path + "/output/test.xml")}