#!/bin/bash

echo ""
% for node in session.query(db.Node).filter(db.Node.tags.contains(['user-adam'])):

echo "[ID: ${node.id}] Name: ${node.instance_name} || Connection: ${node.username}@${node.public_ip} || Provider: ${node.provider}"
% endfor
echo ""