.TH "OGC EXEC-SCRIPTS" "1" "2022-03-31" "2.0.14" "ogc exec-scripts Manual"
.SH NAME
ogc\-exec-scripts \- (R)Execute a set of scripts
.SH SYNOPSIS
.B ogc exec-scripts
[OPTIONS] PATH
.SH DESCRIPTION
(R)Execute a set of scripts
.SH OPTIONS
.TP
\fB\-\-by\-tag\fP TEXT
Only run on nodes matching tag
.TP
\fB\-\-by\-name\fP TEXT
Only run on nodes matching name
