.TH "OGC LS" "1" "2022-03-25" "2.0.4" "ogc ls Manual"
.SH NAME
ogc\-ls \- List nodes in your inventory
.SH SYNOPSIS
.B ogc ls
[OPTIONS]
.SH DESCRIPTION
List nodes in your inventory
.SH OPTIONS
.TP
\fB\-\-by\-tag\fP TEXT
List nodes by tag
.TP
\fB\-\-by\-name\fP TEXT
List nodes by name, this can be a substring match
