.TH "OGC PUSH-FILES" "1" "2022-03-31" "2.0.14" "ogc push-files Manual"
.SH NAME
ogc\-push-files \- Scp files or directories to node
.SH SYNOPSIS
.B ogc push-files
[OPTIONS] NAME SRC DST
.SH DESCRIPTION
Scp files or directories to node
.SH OPTIONS
.TP
\fB\-\-exclude\fP TEXT
Exclude files/directories when uploading
