.TH "OGC LAUNCH" "1" "2022-03-25" "2.0.4" "ogc launch Manual"
.SH NAME
ogc\-launch \- Launches nodes from a provision specification
.SH SYNOPSIS
.B ogc launch
[OPTIONS]
.SH DESCRIPTION
Launches nodes from a provision specification
.SH OPTIONS
.TP
\fB\-\-spec\fP TEXT
.PP
.TP
\fB\-\-with\-deploy\fP / \-\-with\-no\-deploy
Also performs script deployments (default: Yes)
