.TH "OGC EXEC" "1" "2022-03-24" "2.0.0" "ogc exec Manual"
.SH NAME
ogc\-exec \- Execute a command across node(s)
.SH SYNOPSIS
.B ogc exec
[OPTIONS] CMD
.SH DESCRIPTION
Execute a command across node(s)
.SH OPTIONS
.TP
\fB\-\-by\-tag\fP TEXT
Only run on nodes matching tag
.TP
\fB\-\-by\-name\fP TEXT
Only run on nodes matching name
