.TH "OGC STATUS" "1" "2022-04-03" "2.0.14" "ogc status Manual"
.SH NAME
ogc\-status \- Get status of deployment
.SH SYNOPSIS
.B ogc status
[OPTIONS]
.SH DESCRIPTION
Get status of deployment
.SH OPTIONS
.TP
\fB\-\-reconcile\fP / \-\-no\-reconcile
Attempt to fix deployment to match scale
.TP
\fB\-\-spec\fP TEXT
.PP
