.TH "OGC LS" "1" "2022-04-05" "2.0.14" "ogc ls Manual"
.SH NAME
ogc\-ls \- List nodes in your inventory
.SH SYNOPSIS
.B ogc ls
[OPTIONS]
.SH DESCRIPTION
List nodes in your inventory
.SH OPTIONS
.TP
\fB\-\-by\-tag\fP TEXT
List nodes by tag
.TP
\fB\-\-by\-name\fP TEXT
List nodes by name, this can be a substring match
.TP
\fB\-\-output\-file\fP TEXT
Stores the table output to svg or html. Determined by the file extension.
