.TH "OGC RM-KEY-PAIRS" "1" "2022-03-31" "2.0.14" "ogc rm-key-pairs Manual"
.SH NAME
ogc\-rm-key-pairs \- Remove keypairs
.SH SYNOPSIS
.B ogc rm-key-pairs
[OPTIONS]
.SH DESCRIPTION
Remove keypairs
.SH OPTIONS
.TP
\fB\-\-filter\fP TEXT
Filter by keypair name
.TP
\fB\-\-provider\fP TEXT
Provider to query
