.TH "OGC INSPECT" "1" "2022-03-30" "2.0.14" "ogc inspect Manual"
.SH NAME
ogc\-inspect \- List nodes in your inventory
.SH SYNOPSIS
.B ogc inspect
[OPTIONS]
.SH DESCRIPTION
List nodes in your inventory
.SH OPTIONS
.TP
\fB\-\-id\fP TEXT
Inspect node by DB ID
.TP
\fB\-\-name\fP TEXT
Inspect nodes by name, this can be a substring match
.TP
\fB\-\-tag\fP TEXT
Inspect nodes by tag
.TP
\fB\-\-action\-id\fP TEXT
If set will only show the action output for a specific action ID
