.TH "OGC RM" "1" "2022-04-03" "2.0.14" "ogc rm Manual"
.SH NAME
ogc\-rm \- Destroys a node and its associated keys,...
.SH SYNOPSIS
.B ogc rm
[OPTIONS]
.SH DESCRIPTION
Destroys a node and its associated keys, storage, etc.
.SH OPTIONS
.TP
\fB\-\-by\-name\fP TEXT
Remove node by its Name
.TP
\fB\-\-force\fP / \-\-no\-force
Force removal regardless of connectivity
.TP
\fB\-\-only\-db\fP / \-\-no\-only\-db
Force removal of database records only
