.TH "OGC RM" "1" "2022-03-30" "2.0.12" "ogc rm Manual"
.SH NAME
ogc\-rm \- Destroys a node and its associated keys,...
.SH SYNOPSIS
.B ogc rm
[OPTIONS]
.SH DESCRIPTION
Destroys a node and its associated keys, storage, etc.
.SH OPTIONS
.TP
\fB\-\-name\fP TEXT
[required]
.TP
\fB\-\-force\fP / \-\-no\-force
Force removal regardless of connectivity
