.TH "OGC" "1" "2022-03-24" "2.0.4" "ogc Manual"
.SH NAME
ogc \- Just a simple provisioner
.SH SYNOPSIS
.B ogc
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
Just a simple provisioner
.SH COMMANDS
.PP
\fBrm\fP
  Destroys a node and its associated keys,...
  See \fBogc-rm(1)\fP for full documentation on the \fBrm\fP command.
.PP
\fBrm-all\fP
  Destroys everything.
  See \fBogc-rm-all(1)\fP for full documentation on the \fBrm-all\fP command.
.PP
\fBrm-key-pairs\fP
  Remove keypairs
  See \fBogc-rm-key-pairs(1)\fP for full documentation on the \fBrm-key-pairs\fP command.
.PP
\fBinspect\fP
  List nodes in your inventory
  See \fBogc-inspect(1)\fP for full documentation on the \fBinspect\fP command.
.PP
\fBlaunch\fP
  Launches nodes from a provision specification
  See \fBogc-launch(1)\fP for full documentation on the \fBlaunch\fP command.
.PP
\fBls\fP
  List nodes in your inventory
  See \fBogc-ls(1)\fP for full documentation on the \fBls\fP command.
.PP
\fBls-key-pairs\fP
  List keypairs
  See \fBogc-ls-key-pairs(1)\fP for full documentation on the \fBls-key-pairs\fP command.
.PP
\fBlog\fP
  Stream log output
  See \fBogc-log(1)\fP for full documentation on the \fBlog\fP command.
.PP
\fBserver\fP
  Starts the tasks server
  See \fBogc-server(1)\fP for full documentation on the \fBserver\fP command.
.PP
\fBssh\fP
  Login to a node
  See \fBogc-ssh(1)\fP for full documentation on the \fBssh\fP command.
.PP
\fBpush-files\fP
  Scp files or directories to node
  See \fBogc-push-files(1)\fP for full documentation on the \fBpush-files\fP command.
.PP
\fBpull-files\fP
  Scp files or directories from node
  See \fBogc-pull-files(1)\fP for full documentation on the \fBpull-files\fP command.
.PP
\fBpull-artifacts\fP
  Download artifacts from node
  See \fBogc-pull-artifacts(1)\fP for full documentation on the \fBpull-artifacts\fP command.
.PP
\fBexec\fP
  Execute a command across node(s)
  See \fBogc-exec(1)\fP for full documentation on the \fBexec\fP command.
.PP
\fBstatus\fP
  Get status of deployment
  See \fBogc-status(1)\fP for full documentation on the \fBstatus\fP command.
