version: "3.9"

services:
  redis:
    env_file:
      - ".env"
    image: "redis:6.2-alpine"
    restart: always
    volumes:
      - "redis:/data"
    ports:
      - '6379:6379'  

  celery:
    build: 
      context: "."
      dockerfile: Dockerfile.celery
    command: celery -A ogc.celery.app worker -l info -E
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL="redis://redis:6379"
      - CELERY_RESULT_BACKEND="redis://redis:6379"
    volumes:
      - .:/code

volumes:
  redis: {}