[Info]
name = "ogc spec"
description = "OGC tests itself :)"

[[Runner]]
name = "Test ogc core"
description = "This performs unittests for OGC"
entry_point = ["pytest"]

[[Runner]]
name = "Docs"
description = """
Builds the site documentation, including a readme.
"""
entry_point = ["python3"]
args = ['tools/docgen']
tags = ['docs']