"""Fix backref

Revision ID: 74ec3efdd65e
Revises: e4b99ddb88c5
Create Date: 2022-03-30 11:28:45.135043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74ec3efdd65e'
down_revision = 'e4b99ddb88c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
