"""Added user table, expand attributes in nodes

Revision ID: e4b99ddb88c5
Revises: 
Create Date: 2022-03-30 11:23:24.946840

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e4b99ddb88c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('extra', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('actions', sa.Column('extra', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('node', sa.Column('layout', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('node', sa.Column('extra', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('node', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'node', 'user', ['user_id'], ['id'])
    op.drop_column('node', 'uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node', sa.Column('uuid', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'node', type_='foreignkey')
    op.drop_column('node', 'user_id')
    op.drop_column('node', 'extra')
    op.drop_column('node', 'layout')
    op.drop_column('actions', 'extra')
    op.drop_table('user')
    # ### end Alembic commands ###
