#!/bin/bash

echo "My cluster ip connection is ${cluster["username"]}@${cluster["host"]}"
echo "My elastic-agent-ubuntu connection is ${elastic_agent_ubuntu["username"]}@${elastic_agent_ubuntu["host"]}"